#!/usr/bin/env bash
# scripts/render-assets.sh
#
# Renders all PNG assets from assets/logo.svg using the best available tool.
# Priority: Inkscape → rsvg-convert → Python/cairosvg → Python/Pillow (placeholder quality)
#
# Run this whenever assets/logo.svg or assets/logo-dark.svg changes.
#
# Usage:
#   bash scripts/render-assets.sh
#
# Prerequisites (one of):
#   sudo dnf install inkscape                   # best quality
#   sudo dnf install librsvg2-tools             # good quality, fast
#   pip install cairosvg                        # requires libcairo
#   pip install Pillow                          # fallback — no SVG, uses Pillow geometry
# ─────────────────────────────────────────────────────────────────────────────

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
LOGO="$REPO/assets/logo.svg"
LOGO_DARK="$REPO/assets/logo-dark.svg"

# ── Detect renderer ───────────────────────────────────────────────────────────
RENDERER=""

if command -v inkscape &>/dev/null; then
    RENDERER="inkscape"
    echo "[render] Using Inkscape (best quality)"
elif command -v rsvg-convert &>/dev/null; then
    RENDERER="rsvg"
    echo "[render] Using rsvg-convert"
elif python3 -c "import cairosvg" &>/dev/null 2>&1; then
    RENDERER="cairosvg"
    echo "[render] Using cairosvg (Python)"
else
    RENDERER="pillow"
    echo "[render] WARNING: No SVG renderer found — using Pillow placeholder renderer"
    echo "         Install inkscape or librsvg2-tools for proper quality"
fi

render_svg() {
    local src="$1" dest="$2" width="$3" height="$4"
    case "$RENDERER" in
        inkscape)
            inkscape --export-type=png \
                --export-width="$width" --export-height="$height" \
                -o "$dest" "$src" 2>/dev/null
            ;;
        rsvg)
            rsvg-convert -w "$width" -h "$height" "$src" -o "$dest"
            ;;
        cairosvg)
            python3 -c "
import cairosvg
cairosvg.svg2png(url='$src', write_to='$dest', output_width=$width, output_height=$height)
"
            ;;
        pillow)
            # Pillow fallback — cannot render SVG, uses the geometry-based renderer
            python3 "$REPO/scripts/_pillow_render.py" "$dest" "$width" "$height"
            ;;
    esac
    echo "  ✓ $(basename "$dest") (${width}×${height})"
}

# ── Cockpit branding ──────────────────────────────────────────────────────────
echo ""
echo "── Cockpit branding ────────────────────────────────────────────────────"
render_svg "$LOGO" "$REPO/cockpit/logo.png"              225 80
render_svg "$LOGO" "$REPO/cockpit/apple-touch-icon.png"  180 180

# favicon.ico — multi-resolution, needs ImageMagick or Pillow
if command -v convert &>/dev/null; then
    TMPDIR_ICO="$(mktemp -d)"
    render_svg "$LOGO" "$TMPDIR_ICO/16.png" 16 16
    render_svg "$LOGO" "$TMPDIR_ICO/32.png" 32 32
    render_svg "$LOGO" "$TMPDIR_ICO/48.png" 48 48
    convert "$TMPDIR_ICO/16.png" "$TMPDIR_ICO/32.png" "$TMPDIR_ICO/48.png" \
        "$REPO/cockpit/favicon.ico"
    rm -rf "$TMPDIR_ICO"
    echo "  ✓ favicon.ico (16/32/48)"
else
    python3 "$REPO/scripts/_pillow_render.py" favicon "$REPO/cockpit/favicon.ico"
    echo "  ✓ favicon.ico (Pillow)"
fi

# ── Installer pixmaps ─────────────────────────────────────────────────────────
echo ""
echo "── Installer pixmaps ───────────────────────────────────────────────────"
render_svg "$LOGO"      "$REPO/installer/pixmaps/logo.png"         200 60
render_svg "$LOGO_DARK" "$REPO/installer/pixmaps/sidebar-logo.png" 200 60

# Sidebar / topbar backgrounds — generated by Pillow (solid + flame)
python3 "$REPO/scripts/_pillow_render.py" sidebar-bg  "$REPO/installer/pixmaps/sidebar-bg.png"  400 600
python3 "$REPO/scripts/_pillow_render.py" topbar-bg   "$REPO/installer/pixmaps/topbar-bg.png"   800 60
echo "  ✓ sidebar-bg.png (400×600)"
echo "  ✓ topbar-bg.png  (800×60)"

echo ""
echo "All assets rendered. Commit the updated PNGs."
echo "Next: bash scripts/build-product-img.sh"
